# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-13 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('when', models.CharField(default=b'2018-09-12 19:26:52', max_length=200)),
                ('comment', models.TextField()),
                ('commentId', models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('postId', models.CharField(max_length=200)),
                ('anonymity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profilePic', models.ImageField(blank=True, upload_to='Profile Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('when', models.CharField(default=b'2018-09-12 19:26:52', max_length=200)),
                ('post', models.CharField(max_length=10000)),
                ('subject', models.CharField(max_length=1000)),
                ('postId', models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Unresolved', max_length=200)),
                ('anonymity', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Employee'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Post'),
        ),
    ]
