# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='when',
            field=models.CharField(default=b'2018-09-12 19:27:45', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='when',
            field=models.CharField(default=b'2018-09-12 19:27:45', max_length=200),
        ),
    ]
