# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-13 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180912_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='when',
            field=models.CharField(default=b'2018-09-12 19:35:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='when',
            field=models.CharField(default=b'2018-09-12 19:35:00', max_length=200),
        ),
    ]
